### PR TITLE
Update to bootstrap 4 beta

### PR DESCRIPTION
**Pull request by coccor**
Updated the templates to bootstrap 4 beta

### CODE REVIEW

**Comment by prog110** [comment]
Hi,

Was away from work for a while now. Will merge and publish over the weekend.

Thanks for the pull request.

Will let u know once the package is published.

**Comment by amankapoor** [comment]
Hi, please merge this. I just downloaded your plugin in vscode and then came here finding why beta is not updated. Regards.

**Comment by prog110** [comment]
Hi,

Sorry for the delay in merging. I have merged the changes & published the newer version of the plugin.

Can you please verify the latest version from vscode & confirm if there are any issues

**Comment by prog110** [comment]
Please raise an issue if there is any trouble with new build

**Pull request closed without merging**
